"""empty message

Revision ID: 1a4690167c5a
Revises: 4d9f4a620c27
Create Date: 2016-12-06 14:14:03.857000

"""

# revision identifiers, used by Alembic.
revision = '1a4690167c5a'
down_revision = '4d9f4a620c27'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
