"""empty message

Revision ID: 4d9f4a620c27
Revises: 456a945560f6
Create Date: 2016-12-05 17:08:25.009000

"""

# revision identifiers, used by Alembic.
revision = '4d9f4a620c27'
down_revision = '456a945560f6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('confirmed', sa.Boolean(), nullable=True))
    op.add_column('roles', sa.Column('default', sa.Boolean(), nullable=True))
    op.add_column('roles', sa.Column('permissions', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_column('roles', 'permissions')
    op.drop_column('roles', 'default')
    op.drop_column('roles', 'confirmed')
    ### end Alembic commands ###
