"""empty message

Revision ID: 5ae146762728
Revises: 288cd3dc5a8
Create Date: 2017-01-26 11:21:12.014000

"""

# revision identifiers, used by Alembic.
revision = '5ae146762728'
down_revision = '288cd3dc5a8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
