"""empty message

Revision ID: 86691c292b87
Revises: 1b966e7f4b9e
Create Date: 2017-01-25 11:14:40.330000

"""

# revision identifiers, used by Alembic.
revision = '86691c292b87'
down_revision = '1b966e7f4b9e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
