"""empty message

Revision ID: abfe83f9c486
Revises: 86691c292b87
Create Date: 2017-01-25 11:19:58.897000

"""

# revision identifiers, used by Alembic.
revision = 'abfe83f9c486'
down_revision = '86691c292b87'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
